name: Deployment Tagger
description: Tags a commit to be deployed with a deployment version tag.

inputs:
  dev-branch:
    description: 'The branch that feature changes are merged to and from where a release is cut. Default: `develop`'
    type: string
    required: false
    default: 'develop'
  suffix:
    description: 'A suffix to add to the version tag in addition to the repo name, may be empty. Default: empty'
    type: string
    required: false
outputs:
  tag_value:
    description: 'Generated version tag.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          README.md
        sparse-checkout-cone-mode: false

    - name: Set GitHub Path
      run: |
        echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        pwd
        ls -lahR
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - id: compute-and-tag
      shell: bash
      run: |
        pwd
        ls -lahR
        ./scripts/tag-deployment.sh
