name: Run Reusable Workflow

on:
  push:
    branches:
      - develop
      - master
      - release

jobs:
  call-reusable:
    permissions:
      contents: write
    uses: tier4/WebAutoIaCGitHubActions/.github/workflows/deployment_tagging.yml@main
    with:
      suffix: ''
