name: Tagging workflow.

on:
  push:
    branches:
      - develop
      - master
      - release

jobs:
  tag-push:
    permissions:
      contents: write
    uses: ./.github/actions/tag-deployment@develop
    with:
      suffix: ''
