name: Tagging workflow.

on:
  push:
    branches:
      - develop
      - master
      - release

jobs:
  tag-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tag-deployment
        with:
          suffix: ''
