name: Run Reusable Workflow

on:
  push:
    branches:
      - develop
      - master
      - release

jobs:
  call-reusable:
    uses: ./.github/workflows/deployment_tagging.yml
    with:
      suffix: 'submodule'
